version: '3.9'
services:
  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    container_name: travel-api-swagger
    environment:
      URLS: '[{"url":"/openapi/flight.yaml","name":"FlightAPI"},{"url":"/openapi/hotel.yaml","name":"HotelAPI"},{"url":"/openapi/Transfer.yaml","name":"TransferAPI"},{"url":"/openapi/e-sim.yaml","name":"e-simAPI"},]'
    ports:
      - "8080:8080"
    volumes:
      - ../openapi:/usr/share/nginx/html/openapi:ro
    restart: unless-stopped
